name: Destroy Infrastructure
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: tfvars & build lambda package
        env:
          TFVARS: ${{ vars.TFVARS }}
        run: |
          echo $TFVARS > ./generated/terraform/terraform.tfvars
          make build
          mkdir -p ./generated/terraform/build
          cp build/* ./generated/terraform/build/
          echo 'terraform {
            backend "s3" {}
          }' > ./generated/terraform/backend.tf
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ github.repository }}/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}"
        working-directory: ./generated/terraform
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./generated/terraform
